In [214]:
import pandas as pd
import sqlite3

In [215]:
conn = sqlite3.connect('era5_database.sqlite')

weather_df = pd.read_sql("SELECT * FROM city_weather", conn)

weather_df.head()

,time,latitude,longitude,number,step,depthBelowLandLayer,valid_time,stl1,surface,slt,sp,sd,u10,v10,t2m,d2m,sf,e,ro,tp
0,2021-01-01 06:00:00,35.75,139.75,0,0 days,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,-0.000041,0.000015,0.000065
1,2021-01-01 12:00:00,35.75,139.75,0,0 days,0.0,2021-01-01 12:00:00,279.91925,0.0,3.0,101900.016,0.000084,0.187966,-2.449815,277.37920,272.67170,NaN,NaN,NaN,NaN
2,2021-02-01 06:00:00,35.75,139.75,0,0 days,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.980232e-08,-0.000041,0.000011,0.000005
3,2021-02-01 12:00:00,35.75,139.75,0,0 days,0.0,2021-02-01 12:00:00,281.76420,0.0,3.0,101633.664,0.000000,0.555573,-0.719503,280.37323,273.26367,NaN,NaN,NaN,NaN
4,2021-03-01 06:00:00,35.75,139.75,0,0 days,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,-0.000030,0.000009,0.000077

In [216]:
weather_df = weather_df[['time', 'latitude', 'longitude', 'stl1', 'slt', 'sp', 'sd', 'u10', 'v10', 't2m', 'd2m', 'sf', 'e', 'ro', 'tp']]

In [217]:
weather_df.dtypes

time             str
latitude     float64
longitude    float64
stl1         float64
slt          float64
sp           float64
sd           float64
u10          float64
v10          float64
t2m          float64
d2m          float64
sf           float64
e            float64
ro           float64
tp           float64
dtype: object

In [218]:
weather_df['time'] = weather_df['time'].apply(
    lambda x : pd.to_datetime(x[0:10], format='%Y-%m-%d')
)

weather_df.head()

,time,latitude,longitude,stl1,slt,sp,sd,u10,v10,t2m,d2m,sf,e,ro,tp
0,2021-01-01,35.75,139.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,-0.000041,0.000015,0.000065
1,2021-01-01,35.75,139.75,279.91925,3.0,101900.016,0.000084,0.187966,-2.449815,277.37920,272.67170,NaN,NaN,NaN,NaN
2,2021-02-01,35.75,139.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.980232e-08,-0.000041,0.000011,0.000005
3,2021-02-01,35.75,139.75,281.76420,3.0,101633.664,0.000000,0.555573,-0.719503,280.37323,273.26367,NaN,NaN,NaN,NaN
4,2021-03-01,35.75,139.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,-0.000030,0.000009,0.000077

In [219]:
weather_df = weather_df.groupby(['time', 'latitude', 'longitude']).max().reset_index()

weather_df.head()

,time,latitude,longitude,stl1,slt,sp,sd,u10,v10,t2m,d2m,sf,e,ro,tp
0,2021-01-01,-90.00,0.00,232.94269,1.0,68938.016,10.000000,0.380349,0.006728,244.23468,240.34161,0.000002,3.189780e-07,0.000000e+00,0.000002
1,2021-01-01,-77.75,166.75,267.34894,0.0,96918.016,4.021423,-1.187522,-0.171983,268.30695,263.42755,0.000030,-1.464179e-05,0.000000e+00,0.000030
2,2021-01-01,-37.75,145.00,292.26690,4.0,100400.016,0.000000,0.876931,2.148818,290.45734,286.12677,0.000000,-3.708294e-05,1.072884e-06,0.000082
3,2021-01-01,-34.50,301.50,298.18097,0.0,101219.016,0.000000,-0.640159,-0.776475,296.24054,289.96466,0.000000,-2.151071e-04,1.192093e-07,0.000067
4,2021-01-01,-34.00,18.50,295.90167,1.0,100912.016,0.000000,0.170388,5.962783,294.80304,288.18146,0.000000,-6.900122e-05,0.000000e+00,0.000003

In [220]:
weather_df.columns = ['date', 'latitude', 'longitude', 'soil_temperature_level_1', 'soil_type', 'surface_pressure', 'snow_depth', 
    'u_wind_10m', 'v_wind_10m', 'temperature_2m', 'dewpoint_temperature_2m', 'snowfall', 'evaporation', 'runoff', 'total_percipitation']

weather_df.head()

,date,latitude,longitude,soil_temperature_level_1,soil_type,surface_pressure,snow_depth,u_wind_10m,v_wind_10m,temperature_2m,dewpoint_temperature_2m,snowfall,evaporation,runoff,total_percipitation
0,2021-01-01,-90.00,0.00,232.94269,1.0,68938.016,10.000000,0.380349,0.006728,244.23468,240.34161,0.000002,3.189780e-07,0.000000e+00,0.000002
1,2021-01-01,-77.75,166.75,267.34894,0.0,96918.016,4.021423,-1.187522,-0.171983,268.30695,263.42755,0.000030,-1.464179e-05,0.000000e+00,0.000030
2,2021-01-01,-37.75,145.00,292.26690,4.0,100400.016,0.000000,0.876931,2.148818,290.45734,286.12677,0.000000,-3.708294e-05,1.072884e-06,0.000082
3,2021-01-01,-34.50,301.50,298.18097,0.0,101219.016,0.000000,-0.640159,-0.776475,296.24054,289.96466,0.000000,-2.151071e-04,1.192093e-07,0.000067
4,2021-01-01,-34.00,18.50,295.90167,1.0,100912.016,0.000000,0.170388,5.962783,294.80304,288.18146,0.000000,-6.900122e-05,0.000000e+00,0.000003

In [221]:
city_df = pd.read_csv('cities.csv')

city_df.head()

               location continent  latitude  longitude
0          Tokyo, Japan      Asia     35.75     139.75
1  Singapore, Singapore      Asia      1.25     103.75
2            Dubai, UAE      Asia     25.25      55.25
3        Beijing, China      Asia     40.00     116.50
4         Mumbai, India      Asia     19.00      73.00

In [222]:
full_df = weather_df.merge(city_df, how='left', on=['longitude', 'latitude'])

full_df.head()

,date,latitude,longitude,soil_temperature_level_1,soil_type,surface_pressure,snow_depth,u_wind_10m,v_wind_10m,temperature_2m,dewpoint_temperature_2m,snowfall,evaporation,runoff,total_percipitation,location,continent
0,2021-01-01,-90.00,0.00,232.94269,1.0,68938.016,10.000000,0.380349,0.006728,244.23468,240.34161,0.000002,3.189780e-07,0.000000e+00,0.000002,"Amundsen-Scott, Antarctica",Antarctica
1,2021-01-01,-77.75,166.75,267.34894,0.0,96918.016,4.021423,-1.187522,-0.171983,268.30695,263.42755,0.000030,-1.464179e-05,0.000000e+00,0.000030,"McMurdo Station, Antarctica",Antarctica
2,2021-01-01,-37.75,145.00,292.26690,4.0,100400.016,0.000000,0.876931,2.148818,290.45734,286.12677,0.000000,-3.708294e-05,1.072884e-06,0.000082,"Melbourne, Australia",Oceania
3,2021-01-01,-34.50,301.50,298.18097,0.0,101219.016,0.000000,-0.640159,-0.776475,296.24054,289.96466,0.000000,-2.151071e-04,1.192093e-07,0.000067,"Buenos Aires, Argentina",South America
4,2021-01-01,-34.00,18.50,295.90167,1.0,100912.016,0.000000,0.170388,5.962783,294.80304,288.18146,0.000000,-6.900122e-05,0.000000e+00,0.000003,"Cape Town, South Africa",Africa

In [223]:
full_df['soil_type'] = full_df['soil_type'].astype('int64')

full_df = full_df[['location', 'continent', 'date', 'latitude', 'longitude', 'temperature_2m', 'surface_pressure', 'dewpoint_temperature_2m'
    , 'v_wind_10m', 'u_wind_10m', 'evaporation', 'runoff', 'total_percipitation', 'snowfall', 'snow_depth', 'soil_temperature_level_1', 'soil_type']]

full_df.head()

,location,continent,date,latitude,longitude,temperature_2m,surface_pressure,dewpoint_temperature_2m,v_wind_10m,u_wind_10m,evaporation,runoff,total_percipitation,snowfall,snow_depth,soil_temperature_level_1,soil_type
0,"Amundsen-Scott, Antarctica",Antarctica,2021-01-01,-90.00,0.00,244.23468,68938.016,240.34161,0.006728,0.380349,3.189780e-07,0.000000e+00,0.000002,0.000002,10.000000,232.94269,1
1,"McMurdo Station, Antarctica",Antarctica,2021-01-01,-77.75,166.75,268.30695,96918.016,263.42755,-0.171983,-1.187522,-1.464179e-05,0.000000e+00,0.000030,0.000030,4.021423,267.34894,0
2,"Melbourne, Australia",Oceania,2021-01-01,-37.75,145.00,290.45734,100400.016,286.12677,2.148818,0.876931,-3.708294e-05,1.072884e-06,0.000082,0.000000,0.000000,292.26690,4
3,"Buenos Aires, Argentina",South America,2021-01-01,-34.50,301.50,296.24054,101219.016,289.96466,-0.776475,-0.640159,-2.151071e-04,1.192093e-07,0.000067,0.000000,0.000000,298.18097,0
4,"Cape Town, South Africa",Africa,2021-01-01,-34.00,18.50,294.80304,100912.016,288.18146,5.962783,0.170388,-6.900122e-05,0.000000e+00,0.000003,0.000000,0.000000,295.90167,1

In [224]:
full_df.to_csv('city_weather.csv')